// ============================================================
// SciLab - Physics Laboratory
// ============================================================

const labs = [
 { id:'lens', route:'physics-lens', number:'01', title:'Lens & Ray Optics Lab', subtitle:'Optics', icon:'🔍', category:'Optics', desc:'Investigate focal length, object distance, ray paths, image distance and magnification.' },
 { id:'magnetic', route:'physics-magnetic', number:'02', title:'Magnetic Induction Simulator', subtitle:'Electromagnetism', icon:'🧲', category:'Electromagnetism', desc:'Move a magnet through a coil and observe induced EMF, current, flux and power.' },
 { id:'motor', route:'physics-motor', number:'03', title:'Electric Motor Simulator', subtitle:'Electromagnetism', icon:'⚙️', category:'Electromagnetism', desc:'Explore how current in a magnetic field produces torque and rotation.' },
 { id:'solar', route:'physics-solar-system', number:'04', title:'3D Solar System Simulator', subtitle:'Astronomy', icon:'☀️', category:'Astronomy', desc:'Explore planetary orbits, distances, orbital periods and relative motion in 3D.' },
 { id:'virtual', route:'physics-virtual-lab', number:'05', title:'Virtual Physics Lab', subtitle:'Experimental Physics', icon:'🔬', category:'Virtual Lab', desc:'Run classroom-style experiments with live measurements, graphs and teacher guidance.' },
];

let filter='All'; let search='';
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
function openLab(route){const clean=String(route||'').trim().replace(/^#/,'');if(!clean)return;history.pushState({page:clean},'',`#${clean}`);window.dispatchEvent(new PopStateEvent('popstate',{state:{page:clean}}));}
function renderCards(){const grid=document.getElementById('physics-grid');if(!grid)return;const q=search.trim().toLowerCase();const list=labs.filter(x=>(filter==='All'||x.category===filter)&&(!q||[x.title,x.subtitle,x.category,x.desc].join(' ').toLowerCase().includes(q)));grid.innerHTML=list.map((x,i)=>`<article class="physics-hub-card" style="--delay:${i*60}ms"><div class="physics-hub-visual"><div class="physics-hub-orbit"></div><div class="physics-hub-icon">${x.icon}</div><span>${x.number}</span><small>READY</small></div><div class="physics-hub-body"><div class="physics-hub-meta"><span>${esc(x.category)}</span><span>${esc(x.subtitle)}</span></div><h2>${esc(x.title)}</h2><p>${esc(x.desc)}</p><div class="physics-hub-tags"><span>✓ Interactive</span><span>✓ 3D</span><span>✓ Teacher Ready</span></div><button class="physics-hub-open" data-route="${esc(x.route)}">Open Laboratory <strong>→</strong></button></div></article>`).join('');grid.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();openLab(b.dataset.route);}));document.getElementById('physics-count').textContent=`${list.length} laboratories available`;}
function renderFilters(){const el=document.getElementById('physics-filters');if(!el)return;['All','Optics','Electromagnetism','Astronomy','Virtual Lab'].forEach(()=>{});const fs=['All','Optics','Electromagnetism','Astronomy','Virtual Lab'];el.innerHTML=fs.map(f=>`<button class="physics-filter ${f===filter?'is-active':''}" data-f="${esc(f)}">${esc(f)}</button>`).join('');el.querySelectorAll('[data-f]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.f;renderFilters();renderCards();}));}
export function Physics(){setTimeout(()=>{renderFilters();document.getElementById('physics-search')?.addEventListener('input',e=>{search=e.target.value;renderCards();});document.getElementById('physics-reset')?.addEventListener('click',()=>{filter='All';search='';document.getElementById('physics-search').value='';renderFilters();renderCards();});renderCards();},0);return `<section class="physics-page" id="physics-page"><header class="physics-hub-header"><div><span>SCILAB • PHYSICS LABORATORY</span><h1>Physics <em>Interactive Labs</em></h1><p>Explore optics, electromagnetism, astronomy and experimental physics through polished interactive laboratories.</p><div class="physics-hub-badges"><b>05 LABS</b><b>3D EXPERIENCES</b><b>LIVE DATA</b></div></div><div class="physics-hub-orb"><div>⚛️</div><span>PHYSICS</span></div></header><section class="physics-hub-toolbar"><div><span>PHYSICS LABS</span><h2>Choose a laboratory</h2></div><span id="physics-count">5 laboratories available</span><div class="physics-search-row"><input id="physics-search" type="search" placeholder="Search physics laboratories..."/><button id="physics-reset">Reset</button></div><div id="physics-filters" class="physics-filters"></div></section><main id="physics-grid" class="physics-hub-grid"></main><section class="physics-teacher-banner"><div>👨‍🏫</div><div><span>TEACHER READY</span><h2>Physics through interaction</h2><p>Use the laboratories to demonstrate physical laws, change parameters, observe measurements and guide students through scientific reasoning.</p></div><aside><b>05</b><small>LABS</small><b>LIVE</b><small>DATA</small><b>3D</b><small>VISUALS</small></aside></section></section>`;}
export default Physics;
